import type {
  Channel,
  Lead,
  LeadComment,
  LeadEvent,
  Message,
  NewsItem,
  Person,
} from "../types";

/**
 * Seed content for the local development store.
 *
 * Placeholder people and invented hotels. Real rosters and real prospect
 * contact details must never be committed to this repository, which is why the
 * example addresses all resolve to example domains. Replace the roster through
 * /admin once the app runs against Supabase.
 */

export const SEED_PEOPLE: Person[] = [
  {
    id: "p-ahk",
    name: "Akram Hkiri",
    email: "ahk@quinta.im",
    role: "admin",
    territory: null,
    initials: "AH",
    active: true,
  },
  {
    id: "p-mmi",
    name: "Maria Mina",
    email: "mmi@example.quinta.im",
    role: "sales",
    territory: "MMI",
    initials: "MM",
    active: true,
  },
  {
    id: "p-cme",
    name: "Camille Mercier",
    email: "cme@example.quinta.im",
    role: "sales",
    territory: "CME",
    initials: "CM",
    active: true,
  },
  {
    id: "p-dsp",
    name: "Diego Sanz",
    email: "dsp@example.quinta.im",
    role: "sales",
    territory: "DSP",
    initials: "DS",
    active: true,
  },
  {
    id: "p-lwa",
    name: "Lena Walter",
    email: "lwa@example.quinta.im",
    role: "consultant",
    territory: "LWA",
    initials: "LW",
    active: true,
  },
  {
    id: "p-vta",
    name: "Victor Tanaka",
    email: "vta@example.quinta.im",
    role: "consultant",
    territory: "VTA",
    initials: "VT",
    active: true,
  },
  {
    id: "p-sro",
    name: "Sofia Rossi",
    email: "sro@example.quinta.im",
    role: "consultant",
    territory: "SRO",
    initials: "SR",
    active: true,
  },
];

export const SEED_CHANNELS: Channel[] = [
  {
    id: "c-general",
    name: "General",
    slug: "general",
    description: "Anything that does not belong anywhere else.",
  },
  {
    id: "c-handover",
    name: "Lead handover",
    slug: "handover",
    description: "Questions on leads moving between sales and consultants.",
  },
  {
    id: "c-wins",
    name: "Wins",
    slug: "wins",
    description: "Closed deals and things worth copying.",
  },
];

/*
 * Timestamps are fixed rather than derived from the current time, so the seeded
 * state is deterministic and screenshots stay stable between runs.
 */
export const SEED_LEADS: Lead[] = [
  {
    id: "l-1001",
    createdAt: "2026-08-24T09:12:00.000Z",
    createdBy: "p-lwa",
    direction: "for_sales",
    hotelName: "Hotel des Quatre Vents",
    website: "https://quatrevents.example",
    city: "Annecy",
    country: "France",
    rooms: 62,
    contactName: "Elise Brun",
    contactEmail: "e.brun@quatrevents.example",
    contactPhone: "+33 4 50 00 00 00",
    productInterest: "Velma",
    context:
      "Met the GM at a regional hospitality meetup. They run a chatbot that cannot answer room questions and the front desk is drowning in the same five emails. Warm, and expecting a call this week.",
    priority: "high",
    status: "new",
    assignedTo: null,
    hubspotContactId: null,
    hubspotCompanyId: null,
    hubspotDealId: null,
    hubspotSyncedAt: null,
    hubspotSyncError: null,
  },
  {
    id: "l-1002",
    createdAt: "2026-08-26T14:40:00.000Z",
    createdBy: "p-mmi",
    direction: "for_consultant",
    hotelName: "Gran Via Suites",
    website: "https://granviasuites.example",
    city: "Madrid",
    country: "Spain",
    rooms: 140,
    contactName: "Pablo Ortega",
    contactEmail: "p.ortega@granviasuites.example",
    contactPhone: null,
    productInterest: "Q-Data",
    context:
      "Deal is stalled on a technical objection I cannot answer. They want to know how Q-Data handles their four room types with seasonal naming. Need a consultant on the next call.",
    priority: "high",
    status: "claimed",
    assignedTo: "p-vta",
    hubspotContactId: null,
    hubspotCompanyId: null,
    hubspotDealId: null,
    hubspotSyncedAt: null,
    hubspotSyncError: null,
  },
  {
    id: "l-1003",
    createdAt: "2026-08-27T08:05:00.000Z",
    createdBy: "p-sro",
    direction: "for_sales",
    hotelName: "The Lint Quarter",
    website: "https://lintquarter.example",
    city: "Amsterdam",
    country: "Netherlands",
    rooms: 88,
    contactName: "Joost Meijer",
    contactEmail: "joost@lintquarter.example",
    contactPhone: null,
    productInterest: "Q-Share",
    context:
      "Audit client. Their site has no structured data at all, and they asked without prompting whether we could help them show up in AI answers.",
    priority: "normal",
    status: "in_progress",
    assignedTo: "p-cme",
    hubspotContactId: null,
    hubspotCompanyId: null,
    hubspotDealId: null,
    hubspotSyncedAt: null,
    hubspotSyncError: null,
  },
  {
    id: "l-1004",
    createdAt: "2026-08-18T11:22:00.000Z",
    createdBy: "p-vta",
    direction: "for_sales",
    hotelName: "Palazzo Sereno",
    website: "https://palazzosereno.example",
    city: "Florence",
    country: "Italy",
    rooms: 45,
    contactName: "Giulia Fontana",
    contactEmail: "g.fontana@palazzosereno.example",
    contactPhone: "+39 055 000 0000",
    productInterest: "Velma",
    context:
      "Existing Q-Data account, very happy. Asked about adding the chatbot for their second property.",
    priority: "normal",
    status: "won",
    assignedTo: "p-dsp",
    hubspotContactId: null,
    hubspotCompanyId: null,
    hubspotDealId: null,
    hubspotSyncedAt: null,
    hubspotSyncError: null,
  },
  {
    id: "l-1005",
    createdAt: "2026-08-11T16:00:00.000Z",
    createdBy: "p-cme",
    direction: "for_consultant",
    hotelName: "Northgate Airport Hotel",
    website: null,
    city: "Manchester",
    country: "United Kingdom",
    rooms: 210,
    contactName: null,
    contactEmail: null,
    contactPhone: null,
    productInterest: "Q-Data",
    context:
      "Wanted a content audit before committing. Went quiet after the audit was delivered, and later told us they had signed with an incumbent.",
    priority: "low",
    status: "lost",
    assignedTo: "p-lwa",
    hubspotContactId: null,
    hubspotCompanyId: null,
    hubspotDealId: null,
    hubspotSyncedAt: null,
    hubspotSyncError: null,
  },
];

export const SEED_LEAD_EVENTS: LeadEvent[] = [
  { id: "e-1", leadId: "l-1001", actorId: "p-lwa", type: "created", fromStatus: null, toStatus: "new", note: null, createdAt: "2026-08-24T09:12:00.000Z" },
  { id: "e-2", leadId: "l-1002", actorId: "p-mmi", type: "created", fromStatus: null, toStatus: "new", note: null, createdAt: "2026-08-26T14:40:00.000Z" },
  { id: "e-3", leadId: "l-1002", actorId: "p-vta", type: "status_changed", fromStatus: "new", toStatus: "claimed", note: null, createdAt: "2026-08-26T15:02:00.000Z" },
  { id: "e-4", leadId: "l-1003", actorId: "p-sro", type: "created", fromStatus: null, toStatus: "new", note: null, createdAt: "2026-08-27T08:05:00.000Z" },
  { id: "e-5", leadId: "l-1003", actorId: "p-cme", type: "status_changed", fromStatus: "new", toStatus: "claimed", note: null, createdAt: "2026-08-27T09:31:00.000Z" },
  { id: "e-6", leadId: "l-1003", actorId: "p-cme", type: "status_changed", fromStatus: "claimed", toStatus: "in_progress", note: null, createdAt: "2026-08-28T10:00:00.000Z" },
  { id: "e-7", leadId: "l-1004", actorId: "p-vta", type: "created", fromStatus: null, toStatus: "new", note: null, createdAt: "2026-08-18T11:22:00.000Z" },
  { id: "e-8", leadId: "l-1004", actorId: "p-dsp", type: "status_changed", fromStatus: "in_progress", toStatus: "won", note: null, createdAt: "2026-08-29T13:45:00.000Z" },
  { id: "e-9", leadId: "l-1005", actorId: "p-cme", type: "created", fromStatus: null, toStatus: "new", note: null, createdAt: "2026-08-11T16:00:00.000Z" },
  { id: "e-10", leadId: "l-1005", actorId: "p-lwa", type: "status_changed", fromStatus: "in_progress", toStatus: "lost", note: "Signed with incumbent.", createdAt: "2026-08-22T09:00:00.000Z" },
];

export const SEED_LEAD_COMMENTS: LeadComment[] = [
  {
    id: "lc-1",
    leadId: "l-1002",
    authorId: "p-vta",
    body: "Taking this. Their seasonal room naming is the usual trap, so I will put together a two-slide answer before the call.",
    createdAt: "2026-08-26T15:05:00.000Z",
  },
  {
    id: "lc-2",
    leadId: "l-1002",
    authorId: "p-mmi",
    body: "Perfect. Call is Thursday 11:00 CET, I will send the invite.",
    createdAt: "2026-08-26T15:20:00.000Z",
  },
  {
    id: "lc-3",
    leadId: "l-1003",
    authorId: "p-cme",
    body: "Reached out, they replied same day. Sending the Q-Share analysis over.",
    createdAt: "2026-08-28T10:02:00.000Z",
  },
];

export const SEED_MESSAGES: Message[] = [
  {
    id: "m-1",
    channelId: "c-general",
    authorId: "p-ahk",
    body: "Welcome to the Lead Hub. Post a lead here instead of emailing it, and we will finally be able to see where things stand.",
    createdAt: "2026-08-24T08:00:00.000Z",
    editedAt: null,
    mentions: [],
  },
  {
    id: "m-2",
    channelId: "c-general",
    authorId: "p-mmi",
    body: "Long overdue. Can we filter the board by territory later?",
    createdAt: "2026-08-24T08:14:00.000Z",
    editedAt: null,
    mentions: [],
  },
  {
    id: "m-3",
    channelId: "c-handover",
    authorId: "p-lwa",
    body: "Dropped Hotel des Quatre Vents in as a lead for sales. The GM is expecting a call this week, so it is genuinely time sensitive.",
    createdAt: "2026-08-24T09:15:00.000Z",
    editedAt: null,
    mentions: [],
  },
  {
    id: "m-4",
    channelId: "c-handover",
    authorId: "p-cme",
    body: "Seen. Annecy is mine, I will take it this afternoon.",
    createdAt: "2026-08-24T09:40:00.000Z",
    editedAt: null,
    mentions: [],
  },
  {
    id: "m-5",
    channelId: "c-wins",
    authorId: "p-dsp",
    body: "Palazzo Sereno signed for Velma on their second property. The consultant note on the first deal is what made the difference.",
    createdAt: "2026-08-29T13:50:00.000Z",
    editedAt: null,
    mentions: [],
  },
];

export const SEED_NEWS: NewsItem[] = [
  {
    id: "n-1",
    title: "The Lead Hub is live",
    slug: "lead-hub-is-live",
    excerpt: "One place for sales and consultants to pass work to each other.",
    body: [
      "Leads used to move over email, which meant nobody could see who had picked up what, and the person who sourced a lead never heard how it ended.",
      "",
      "The Lead Hub fixes the visible part of that problem. Post a lead, someone claims it, and the outcome comes back to you.",
      "",
      "## What to do differently",
      "",
      "- Post the lead here first, then mention it in chat if it is urgent.",
      "- Claim a lead before you start working it, so two people do not call the same GM.",
      "- Close it out as won or lost. A lost lead with a reason is more useful than a lead that quietly goes stale.",
    ].join("\n"),
    category: "Product",
    authorId: "p-ahk",
    publishedAt: "2026-08-24T07:30:00.000Z",
    pinned: true,
  },
  {
    id: "n-2",
    title: "Consultant notes now travel with the deal",
    slug: "consultant-notes-travel-with-the-deal",
    excerpt: "Why the Palazzo Sereno win started eight months earlier.",
    body: [
      "Palazzo Sereno signed for Velma on their second property this week. The interesting part is not the deal. It is that the consultant note from their original Q-Data onboarding is what closed it.",
      "",
      "When a consultant records what an account actually cares about, the next conversation starts a great deal further along. That is the whole argument for keeping this in one place rather than in individual inboxes.",
    ].join("\n"),
    category: "Wins",
    authorId: "p-dsp",
    publishedAt: "2026-08-29T15:00:00.000Z",
    pinned: false,
  },
  {
    id: "n-3",
    title: "A reminder on prospect data",
    slug: "reminder-on-prospect-data",
    excerpt: "What belongs in a lead, and what does not.",
    body: [
      "The Hub holds real contact details for real people at real hotels, which makes it subject to the same care as the CRM.",
      "",
      "## Keep in",
      "",
      "Name, work email, work phone, and the context a colleague needs to have a useful conversation.",
      "",
      "## Leave out",
      "",
      "Personal mobile numbers, anything told to you in confidence, and speculation about individuals. If you would not want it read back to you in the room, do not type it here.",
    ].join("\n"),
    category: "Policy",
    authorId: "p-ahk",
    publishedAt: "2026-08-30T09:00:00.000Z",
    pinned: false,
  },
];
